// vue/components/form/FormRow.vue
<template>
   <div class="flex items-start flex-wrap w-full" :class="classes">
      <slot></slot>
   </div>
</template>

<script setup lang="ts">
const props = defineProps<{
   colSpan?: ('lg:2' | '2xl:2' | '2xl:3')[] | 'full';
}>();

const classes = computed(() => ({
   'lg:col-span-2 2xl:col-span-3': props.colSpan === 'full',
   '2xl:col-span-3': props.colSpan?.includes('2xl:3'),
   '2xl:col-span-2': props.colSpan?.includes('2xl:2'),
   'lg:col-span-2': props.colSpan?.includes('lg:2'),
}));
</script>

// react/components/common/form/FormRow.tsx
import React, { FC } from 'react';
import { twJoin } from 'tailwind-merge';

interface FormRowProps {
   classnames?: string;
   children: React.ReactNode | React.ReactNode[];
   colSpan?: ('lg:2' | '2xl:2' | '2xl:3')[] | 'full';
}

const FormRow: FC<FormRowProps> = ({ colSpan, classnames, children }) => {
   return (
      <div
         className={twJoin(
            'flex items-start flex-wrap w-full',
            colSpan?.includes('lg:2') && 'lg:col-span-2',
            colSpan?.includes('2xl:2') && '2xl:col-span-2',
            colSpan?.includes('2xl:3') && '2xl:col-span-3',
            colSpan === 'full' && 'lg:col-span-2 2xl:col-span-3',
            classnames || '',
         )}
      >
         {children}
      </div>
   );
};

export default FormRow;
